trigger:
  branches:
    exclude: 
    - u/*
pr:
  branches:
    include:
    - master
    - feature/*

jobs:
- job: Windows
  pool:
    vmImage: windows-latest
  strategy:
    maxParallel: 4
    matrix:
      Release:
        _configuration: Release
  steps:
    - script: init.cmd
      displayName: initialize
      condition: succeeded()
      
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        feedsToUse: 'config'
        nugetConfigPath: 'NuGet.config'
      condition: succeeded()
      displayName: "Restore"

    - task: DotNetCoreCLI@2
      inputs:
        command: 'custom'
        custom: 'msbuild'
        arguments: '-property:Configuration=$(_configuration)
                    -property:BUILDNUMBER=release
                    -bl:./artifacts/log/$(_configuration)/Build.binlog'
      condition: succeeded()
      displayName: Build
    
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        publishTestResults: true
        arguments: '--collect "Code coverage"
                    --no-build
                    -c $(_configuration)
                    --settings "CodeCoverage.runsettings"'
        projects: '**/*.Tests.csproj'
      condition: succeeded()
      
    - task: DotNetCoreCLI@2
      inputs:
        command: 'custom'
        custom: 'pack'
        arguments: '-c $(_configuration)
                    --no-build
                    -property:SymbolPackageFormat=snupkg
                    -property:IncludeSymbols=true
                    -property:BUILDNUMBER=release'
      displayName: Pack
      condition: succeeded()

    - script: Build.cmd -BuildDoc
      displayName: Build Doc site
      continueOnError: true
      condition: and(succeeded(), eq(variables['_configuration'], 'Release'))
    
    # Should always run
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\log\$(_configuration)'
        ArtifactName: '$(_configuration) log folder'
        publishLocation: Container
      continueOnError: true
      condition: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\Packages\$(_configuration)'
        ArtifactName: '$(_configuration) packages folder'
        publishLocation: Container
      displayName: Publish packages folder
      continueOnError: true
      condition: eq(variables['_configuration'], 'Release')

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\docs'
        ArtifactName: 'doc site'
        publishLocation: Container
      displayName: Publish doc folder
      continueOnError: true
      condition: and(succeeded(), eq(variables['_configuration'], 'Release'))

